import makeWASocket, {
    DisconnectReason,
    useMultiFileAuthState,
    fetchLatestBaileysVersion,
    makeCacheableSignalKeyStore,
    WAConnectionState,
} from '@whiskeysockets/baileys';
import { Boom } from '@hapi/boom';
import express from 'express';
import axios from 'axios';
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import pino from 'pino';
import fs from 'fs';
import path from 'path';

dotenv.config();

const logger = pino({ level: 'info' });
const app = express();
app.use(express.json());

// Environment variables
const WEBHOOK_URL = process.env.WEBHOOK_URL || 'http://localhost:10000/api/v1/webhooks/whatsapp';
const WORKSPACE_ID = process.env.WORKSPACE_ID || ''; // Required in production
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = (SUPABASE_URL && SUPABASE_KEY) ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;
const sessionDir = path.resolve(process.cwd(), 'auth_info_baileys');

// ── Supabase Session Sync ──────────────────────────────────────────────────

async function pullSessionFromSupabase() {
    if (!supabase) return;
    try {
        // Only pull creds.json — pre-keys are auto-regenerated by Baileys
        const { data, error } = await supabase
            .from('whatsapp_sessions')
            .select('file_id, data')
            .eq('workspace_id', WORKSPACE_ID)
            .eq('file_id', 'creds.json');

        if (error) throw error;
        if (!data || data.length === 0) {
            logger.info('No persistent session found in Supabase');
            return;
        }

        if (!fs.existsSync(sessionDir)) {
            fs.mkdirSync(sessionDir, { recursive: true });
        }

        for (const item of data) {
            const filePath = path.join(sessionDir, item.file_id);
            fs.writeFileSync(filePath, JSON.stringify(item.data));
        }
        logger.info(`Pulled ${data.length} session files from Supabase`);
    } catch (err) {
        logger.error({ err }, 'Failed to pull session from Supabase');
    }
}

// Debounce map to prevent reading files before they are fully written
const pushTimers: Map<string, ReturnType<typeof setTimeout>> = new Map();

async function pushFileToSupabase(fileId: string) {
    if (!supabase) return;
    try {
        const filePath = path.join(sessionDir, fileId);
        if (!fs.existsSync(filePath)) return;

        const raw = fs.readFileSync(filePath, 'utf-8').trim();
        if (!raw) return;

        let content: any;
        try {
            content = JSON.parse(raw);
        } catch {
            return; // File still being written
        }

        const { error } = await supabase
            .from('whatsapp_sessions')
            .upsert({
                workspace_id: WORKSPACE_ID,
                file_id: fileId,
                data: content,
                updated_at: new Date().toISOString()
            }, { onConflict: 'workspace_id,file_id' });

        if (error) throw error;
    } catch (err) {
        logger.error({ err, fileId }, 'Failed to push session file to Supabase');
    }
}

async function removeSessionFromSupabase() {
    if (!supabase) return;
    try {
        const { error } = await supabase
            .from('whatsapp_sessions')
            .delete()
            .eq('workspace_id', WORKSPACE_ID);
        if (error) throw error;
        logger.info('Cleared persistent session from Supabase');
    } catch (err) {
        logger.error({ err }, 'Failed to clear session from Supabase');
    }
}

// ── WhatsApp Connection Logic ──────────────────────────────────────────────

let sock: any = null;
let qrCode: string | null = null;
let connectionState: string = 'disconnected';

async function connectToWhatsApp() {
    // Pull session before starting
    await pullSessionFromSupabase();

    const { state, saveCreds } = await useMultiFileAuthState(sessionDir);
    const { version, isLatest } = await fetchLatestBaileysVersion();

    sock = makeWASocket({
        version,
        logger: logger as any,
        printQRInTerminal: true,
        auth: {
            creds: state.creds,
            keys: makeCacheableSignalKeyStore(state.keys, logger as any),
        },
    });

    sock.ev.on('connection.update', (update: any) => {
        const { connection, lastDisconnect, qr } = update;

        if (qr) {
            qrCode = qr;
        }

        if (connection === 'close') {
            connectionState = 'disconnected';
            const shouldReconnect = (lastDisconnect?.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut;
            logger.info('connection closed due to ', lastDisconnect?.error, ', reconnecting ', shouldReconnect);
            if (shouldReconnect) {
                connectToWhatsApp();
            }
        } else if (connection === 'open') {
            connectionState = 'connected';
            qrCode = null;
            logger.info('opened connection');
        }
    });

    sock.ev.on('creds.update', async () => {
        await saveCreds();
        // Only persist creds.json — pre-keys are auto-regenerated by Baileys
        await pushFileToSupabase('creds.json');
    });

    sock.ev.on('messages.upsert', async (m: any) => {
        logger.info({ m }, 'Messages upsert received');
        if (m.type === 'notify') {
            for (const msg of m.messages) {
                if (!msg.key.fromMe && msg.message) {
                    const text = msg.message.conversation ||
                        msg.message.extendedTextMessage?.text ||
                        msg.message.imageMessage?.caption;

                    if (text) {
                        try {
                            // Prefer remoteJidAlt (actual phone JID) over remoteJid (can be LID)
                            const resolvedJid = msg.key.remoteJidAlt || msg.key.remoteJid;

                            logger.info({
                                webhook: WEBHOOK_URL,
                                payload: {
                                    chat_id: resolvedJid,
                                    original_jid: msg.key.remoteJid,
                                    alt_jid: msg.key.remoteJidAlt,
                                    text
                                }
                            }, 'Sending webhook');

                            const response = await axios.post(WEBHOOK_URL, {
                                workspace_id: WORKSPACE_ID,
                                chat_id: resolvedJid,
                                from_name: msg.pushName || 'WhatsApp User',
                                text: text,
                                message_id: msg.key.id,
                                metadata: {
                                    timestamp: msg.messageTimestamp
                                }
                            });
                            logger.info({ status: response.status }, 'Webhook sent successfully');
                        } catch (error) {
                            logger.error({ error }, 'Failed to send webhook');
                        }
                    }
                }
            }
        }
    });
}

// API Routes
app.get('/status', (req, res) => {
    res.json({ state: connectionState, qr: qrCode });
});

app.post('/connect', async (req, res) => {
    try {
        // Close any existing socket gracefully
        if (sock) {
            try {
                sock.end(undefined);
            } catch (_) { /* ignore */ }
            sock = null;
        }

        // Clear status
        qrCode = null;
        connectionState = 'disconnected';

        // Clear Supabase persistent session
        await removeSessionFromSupabase();

        // Robust local session clearing (check multiple potential paths)
        const pathsToClear = [
            sessionDir,
            path.join(__dirname, 'auth_info_baileys'),
            path.resolve(process.cwd(), 'auth_info_baileys')
        ];

        for (const p of pathsToClear) {
            if (fs.existsSync(p)) {
                logger.info({ path: p }, 'Clearing session directory');
                fs.rmSync(p, { recursive: true, force: true });
            }
        }

        // Start a fresh connection — this will trigger QR code generation
        await connectToWhatsApp();

        // Wait briefly for QR to be generated
        await new Promise(resolve => setTimeout(resolve, 3000));

        res.json({
            success: true,
            state: connectionState,
            qr: qrCode,
            message: 'Connection restarted, QR code should appear shortly'
        });
    } catch (error) {
        logger.error({ error }, 'Failed to restart connection');
        res.status(500).json({ success: false, error: (error as Error).message });
    }
});

app.post('/send', async (req, res) => {
    const { chat_id, text } = req.body;
    if (!sock || connectionState !== 'connected') {
        return res.status(503).json({ error: 'WhatsApp not connected' });
    }

    try {
        const jid = chat_id.includes('@') ? chat_id : `${chat_id}@s.whatsapp.net`;
        await sock.sendMessage(jid, { text });
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: (err as Error).message });
    }
});

app.post('/logout', async (req, res) => {
    logger.info('Logout requested');
    try {
        if (sock) {
            try {
                await sock.logout();
            } catch (err) {
                logger.warn({ err }, 'Sock logout failed, continuing with cleanup');
            }
            sock = null;
        }

        // Clear Supabase persistent session
        await removeSessionFromSupabase();

        // Robust session clearing (check both potential paths)
        const pathsToClear = [
            sessionDir,
            path.join(__dirname, 'auth_info_baileys'),
            path.resolve(process.cwd(), 'auth_info_baileys'),
            path.join(__dirname, '..', 'auth_info_baileys')
        ];

        for (const p of pathsToClear) {
            if (fs.existsSync(p)) {
                logger.info({ path: p }, 'Clearing session directory');
                fs.rmSync(p, { recursive: true, force: true });
            }
        }

        qrCode = null;
        connectionState = 'disconnected';

        // Return success even if sock was null, as long as we cleared files
        res.json({ success: true, message: 'Logged out and session cleared' });

        // Restart connection to be ready for new login
        connectToWhatsApp().catch(err => logger.error({ err }, 'Error restarting after logout'));
    } catch (error) {
        logger.error({ error }, 'Logout failed');
        res.status(500).json({ success: false, error: (error as Error).message });
    }
});

const PORT = process.env.WHATSAPP_BRIDGE_PORT || 3001; // Moved PORT definition
app.listen(PORT, () => {
    logger.info(`WhatsApp bridge listening on port ${PORT}`);
    connectToWhatsApp();
});
